# Generated by Django 4.2.4 on 2023-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Cost', models.FloatField()),
                ('Mft', models.DateField()),
                ('Exp', models.DateField()),
            ],
        ),
    ]
